name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Deploy'
        required: true
        default: 'prod-deploy'
  push:
    branches:
    tags:

jobs:
  # --- check lint ---------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing depedencies
        run: yarn install
      - name: Running test lint
        run: yarn lint
  # --- build ---------------
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing depedencies
        run: yarn install
      - name: Try to build
        run: yarn build
  # --- deeploy ---------------
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: ${{ github.event.inputs.job == 'dev-deploy'}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing depedencies
        run: yarn install
      - name: Try to build
        run: yarn build
      - name: Deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
