name: Deploy to Vercel

on:
  push:
    branches:
    tags:

jobs:
  # --- install depedencies ---------------
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Installing depedencies
        run: yarn install

  # --- check lint ---------------
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Running Test Lint
        run: yarn lint
