name: Deploy to Vercel

on:
  push:
    branches:
    tags:

jobs:
  # --- check lint ---------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing depedencies
        run: yarn install
      - name: Running test lint
        run: yarn lint
