name: Deploy to Vercel

on:
  push:
    branches:
    tags:

jobs:
  # --- install depedencies ---------------
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing depedencies
        run: yarn install

  test:lint:
    runs-on: ubuntu-latest
    needs: prepare
    - name: Running Test
      run: CI=true yarn test
